# Boardlink Curtain 调试配置文件
# 这个文件用于在本地测试环境中快速配置和调试组件

# 测试用的虚拟窗帘配置
debug_curtain_1:
  name: "测试窗帘1"
  open_code: "JgBQAAABKpIVEhUSFRIVEhUSFRIV..."  # 测试用开启码
  close_code: "JgBQAAABKpMVEhUSFRIVEhUSFRIV..."  # 测试用关闭码
  pause_code: "JgBQAAABKpQVEhUSFRIVEhUSFRIV..."  # 测试用暂停码
  close_time: 10  # 测试用较短的关闭时间
  broadlink_device: "debug_broadlink"  # 测试用设备名
  broadlink_type: "RM_MINI3"

debug_curtain_2:
  name: "模拟窗帘2"
  open_code: "test_open_code"
  close_code: "test_close_code"
  pause_code: "test_pause_code"
  close_time: 5
  broadlink_device: null  # 无Broadlink设备，使用模拟模式

# 调试日志配置
logger:
  default: warning
  logs:
    custom_components.boardlink_curtain: debug
    homeassistant.components.cover: debug