name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    name: Validate with hassfest
    steps:
      - uses: actions/checkout@v4

      - name: Validate
        uses: home-assistant/actions/hassfest@master

  validate-hacs:
    runs-on: ubuntu-latest
    name: Validate with HACS
    steps:
      - uses: actions/checkout@v4

      - name: Validate
        uses: hacs/action@main
        with:
          category: integration